#!/usr/bin/env python3
"""git filter-branch --msg-filter: translate English commit messages to Chinese."""
import sys

sys.stdin.reconfigure(encoding='utf-8', errors='replace')
sys.stdout.reconfigure(encoding='utf-8')

msg = sys.stdin.read()

# Prefix
prefixes = [
    ("feat(optimization):", "新增(优化)："),
    ("feat:", "新增："),
    ("fix:", "修复："),
    ("docs:", "文档："),
    ("chore:", "工程："),
    ("test:", "测试："),
    ("evidence:", "证据："),
    ("merge:", "合并："),
]

# Phrase table
table = [
    ("Initial commit", "初始提交"),
    ("Update README.md", "更新README"),
    ("KylinBootLab full project history", "KylinBootLab完整项目历史"),
    ("complete project history (92 commits)", "完整项目历史（93提交）"),
    ("Phase 1-9 evidence SPA", "Phase 1-9证据仪表板"),
    ("Phase 2 testbed-recovery design spec", "Phase 2自动化冷启动实验台设计方案"),
    ("Phase 2 testbed-recovery implementation plan (10 tasks)", "Phase 2实现计划（10任务）"),
    ("Phase 3 observability-readiness design spec", "Phase 3语义就绪探测设计方案"),
    ("Phase 3 observability-readiness implementation plan (13 tasks)", "Phase 3实现计划（13任务）"),
    ("Phase 3 plan review findings", "Phase 3计划审查发现"),
    ("Phase 4 causal-graph and simulator design spec", "Phase 4因果图与模拟器设计方案"),
    ("Phase 4 causal-graph implementation plan (10 tasks)", "Phase 4实现计划（10任务）"),
    ("Phase 4 reconnaissance", "Phase 4竞态条件勘察"),
    ("Phase 5 optimizer-validator design spec", "Phase 5优化规划器与验证器设计方案"),
    ("Phase 5 optimizer-validator implementation plan", "Phase 5实现计划"),
    ("Phase 5 ABBA acceptance", "Phase 5 ABBA实机验收"),
    ("Phase 6 systemd-kernel optimization design spec", "Phase 6系统与内核优化设计方案"),
    ("Phase 6 systemd-kernel optimization implementation plan (4 tasks)", "Phase 6实现计划（4任务）"),
    ("Phase 6 complete", "Phase 6完成"),
    ("Phase 8 BootAgent design spec", "Phase 8 BootAgent设计方案"),
    ("Phase 8 BootAgent implementation plan (5 tasks)", "Phase 8实现计划（5任务）"),
    ("Phase 9 dashboard components", "Phase 9仪表板前端组件"),
    ("DOT graph + critical-chain + blame + SVG plot", "DOT图+关键链+blame+SVG时序图"),
    ("DOT parser for systemd-analyze output", "systemd DOT图解析器"),
    ("ABBA experiment runner (Phase 2 integration)", "ABBA实验运行器（Phase 2集成）"),
    ("ABBA scheduler, profile state machine, and SSH executor", "ABBA调度器+状态机+SSH执行器"),
    ("candidate scoring engine", "候选评分引擎"),
    ("bootstrap CI + three-tier verdict", "bootstrap置信区间+三级阈值判定"),
    ("bootstrap validator + numpy dependency", "bootstrap验证器+numpy依赖"),
    ("bottleneck ranking engine and WhatIfSimulator", "瓶颈排名引擎+WhatIf模拟器"),
    ("benchmark evaluator + kbl agent CLI", "基准评估器+kbl agent命令行"),
    ("BootAgent four-role controller", "BootAgent四角色控制器"),
    ("CausalGraphBuilder", "因果图构建器"),
    ("critical_path() and slack() algorithms", "关键路径+松弛度算法（拓扑DP）"),
    ("cross-run graph comparison (diff_graphs)", "跨运行图比较（GraphDiff）"),
    ("causal graph data models", "因果图数据模型"),
    ("kbl analyze CLI command for causal graph pipeline", "kbl analyze因果图分析命令行"),
    ("kbl calibrate overhead protocol", "kbl calibrate开销校准协议"),
    ("kbl experiment CLI subcommands", "kbl experiment命令行子命令"),
    ("kbl optimize CLI subcommands", "kbl optimize命令行子命令"),
    ("kbl dashboard command + Phase 9 evidence SPA", "kbl dashboard命令+Phase 9证据仪表板"),
    ("gate collection on observer done marker", "观测器完成标记门控采集"),
    ("combined optimization ABBA", "组合优化ABBA实验"),
    ("PROMISING (+23% floor)", "PROMISING（底限-23%）"),
    ("ABBA experiment mask-biometric", "ABBA实验mask-biometric"),
    ("2 candidates evaluated", "2个候选完成评估"),
    ("5/5 candidates ABBA evaluated", "5/5候选ABBA评估完成"),
    ("cross-distro adapter code + BootAgent output", "跨发行版适配器代码+BootAgent输出"),
    ("comprehensive project README for competition review", "完整项目README（赛题交付）"),
    ("competition task description", "竞赛题目说明"),
    ("cross-distribution adapters + competition technical report", "跨发行版适配器+竞赛技术报告"),
    ("safe target probe setup", "目标机探针安全部署"),
    ("recovery diagram with vmrun revision", "恢复流程图对齐vmrun修订"),
    ("spec 4.3 fast-degrade with enabled-marker probe", "规格4.3快速降级对齐enabled标记探测"),
    ("CLAUDE.md with project summary and onboarding guide", "CLAUDE.md项目总结与入门指南"),
    ("KylinBootLab design", "KylinBootLab设计方案"),
    ("KylinBootLab implementation plans", "KylinBootLab实现计划"),
    ("strengthen performance benefit narrative with best-boot analysis", "强化性能收益叙述：最佳实测启动分析"),
    ("combo experiment to tech report (PROMISING, -23%)", "组合实验加入技术报告（PROMISING，-23%）"),
    ("ExperimentRecord contract", "ExperimentRecord契约模型"),
    ("ReadinessEvent v1 model", "ReadinessEvent v1模型"),
    ("ReadinessEvent contract and T-point derivation", "ReadinessEvent契约+T点派生"),
    ("JSONL ExperimentQueue", "JSONL持久化实验队列"),
    ("TargetPower protocol and VixPower backend", "TargetPower协议+VixPower后端"),
    ("WolPower bare-metal backend", "WolPower裸机后端"),
    ("SSH alive detector", "SSH存活检测器"),
    ("RecoveryManager with double-layer restore", "双层恢复管理器（VIX快照+ostree回退）"),
    ("ExperimentOrchestrator with retrying main loop", "实验编排器（重试主循环）"),
    ("observer systemd unit, autostart, installer, and runbook", "观测器systemd单元+自启动+安装脚本+操作手册"),
    ("ObserveConfig model", "观测器配置模型"),
    ("journald JSON parsing and boot-replay follower", "journald JSON解析+引导回放追随者"),
    ("keymap table and uinput virtual keyboard", "键映射表+uinput虚拟键盘"),
    ("ReadinessState machine and observe driver", "就绪状态机+观测器驱动"),
    ("usable-probe (procscan + AT-SPI + sentinel window detection)", "会话可用探测器（进程扫描+AT-SPI+哨兵检测）"),
    ("observe/usable-probe CLI, readiness capture, xlang fixture parity", "CLI接线+就绪采集+跨语言互验"),
    ("recovery script", "恢复脚本"),
    ("auto-requeue interrupted experiments, clear stale error on success", "中断实验自动重入队+成功时清除残留错误"),
    ("drive VMware power control via vmrun, fail loud on power errors", "改用vmrun驱动VMware电源控制（fail-loud）"),
    ("wait for systemd boot-finished before collecting", "采集前等待systemd启动完成"),
    ("increase usable timeout to 360s for UKUI autostart latency", "延增可用超时至360s（UKUI自启动延迟）"),
    ("replace dbus-send with busctl get-property for AT-SPI ChildCount", "AT-SPI ChildCount改用busctl get-property"),
    ("clippy while_let_loop, TryRecvError import, cargo fmt", "clippy修复+cargo fmt格式化"),
    ("scp-nested duplicate directories", "SCP嵌套重复目录清理"),
    ("sudo password in ProfileExecutor, verify mask via symlink", "ProfileExecutor sudo密码管道+掩码验证"),
    ("add 1s post-apply delay before verify", "应用后延迟1s再验证（systemd缓存）"),
    ("replace all sudo occurrences with password piping", "全部sudo实例注入密码管道"),
    ("type annotations for all dict params in skills.py", "skills.py全部dict参数类型标注"),
    ("aggressive name->node alias, SIM102 nest merge", "移除过度激进的name->node别名映射"),
    ("Address Codex review findings", "处理Codex审查发现（第二轮）"),
    ("address Codex review findings", "处理Codex审查发现（第一轮）"),
    ("add P1 guard tests + kaiming upstream patch note", "P1防护测试+kaiming上游补丁说明"),
    ("test count to over 300 Python + 54 Rust", "修正测试数量：300+Python+54Rust"),
    ("DP critical path (O(V+E)), builder event ordering, CLI DOT fallback", "DP关键路径+事件排序+CLI DOT退路"),
    ("Foundation quality gates", "Phase 1质量门禁"),
    ("Bootstrap the monorepo and Python CLI", "单仓库+Python CLI脚手架"),
    ("Probe Manifest Contract", "探针清单契约定义"),
    ("rust contract types and cross-language parity", "Rust契约类型+跨语言互验"),
    ("target capture primitives", "目标机采集原语"),
    ("capture target boot snapshot", "目标机启动快照采集"),
    ("immutable run store", "不可变RunStore"),
    ("deterministic systemd parsing", "确定性systemd解析"),
    ("baseline boot report", "基线启动报告"),
    ("collect target snapshots over SSH", "SSH远程采集目标机快照"),
    ("observer config parsing", "观测器配置解析"),
    ("ignore local worktrees", "忽略本地工作树"),
    ("ruff auto-fixes on pre-existing scripts", "ruff自动修复预存脚本"),
    ("extend kbl optimize subcommands", "扩展kbl optimize子命令"),
    ("expanded regression matrix", "扩展回归矩阵"),
    ("deliverable cleanup", "交付清理"),
    ("delivery cleanup", "交付清理"),
    ("remove dev docs and temp scripts", "移除开发文档和临时脚本"),
]

for en, zh in prefixes:
    if msg.startswith(en):
        msg = zh + msg[len(en):]
        break

for en, zh in table:
    msg = msg.replace(en, zh)

sys.stdout.write(msg)
